name: "Deploy App"

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/craft-your-knowledge.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: satttoshi
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: satttoshi/craft-your-knowledge:latest
          context: .
          platforms: linux/arm64

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Restart docker container
        uses: appleboy/ssh-action@master
        with:
          host: craft-your-knowledge.joshua-stolle.de
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_SSH_PASSWORD }}
          script: |
            sudo docker stop craft-your-knowledge
            sudo docker rm craft-your-knowledge
            sudo docker run --pull=always --name craft-your-knowledge -p 8080:8080 --restart always --detach --env MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} satttoshi/craft-your-knowledge:latest
            sleep 15s
            sudo docker logs craft-your-knowledge

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://craft-your-knowledge.joshua-stolle.de
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
